# Generated by Django 3.2.9 on 2021-12-29 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ram_app', '0002_jewellery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bangels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bangels_name', models.CharField(default='', max_length=50)),
                ('image', models.ImageField(default='', upload_to='images')),
                ('price', models.IntegerField(default=0)),
                ('pub_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Bracelet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bracelet_name', models.CharField(default='', max_length=50)),
                ('image', models.ImageField(default='', upload_to='images')),
                ('price', models.IntegerField(default=0)),
                ('pub_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Earring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ear_name', models.CharField(default='', max_length=50)),
                ('image', models.ImageField(default='', upload_to='images')),
                ('price', models.IntegerField(default=0)),
                ('pub_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Mangalsutra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mangal_name', models.CharField(default='', max_length=50)),
                ('image', models.ImageField(default='', upload_to='images')),
                ('price', models.IntegerField(default=0)),
                ('pub_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Necklace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neck_name', models.CharField(default='', max_length=50)),
                ('image', models.ImageField(default='', upload_to='images')),
                ('price', models.IntegerField(default=0)),
                ('pub_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Nosepin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nose_name', models.CharField(default='', max_length=50)),
                ('image', models.ImageField(default='', upload_to='images')),
                ('price', models.IntegerField(default=0)),
                ('pub_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='P_blue_sapphire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bs_name', models.CharField(max_length=30)),
                ('image', models.ImageField(default='', upload_to='diamond_images')),
                ('d_color', models.CharField(max_length=30)),
                ('d_clearity', models.CharField(max_length=20)),
                ('d_shape', models.CharField(max_length=20)),
                ('d_carat', models.CharField(max_length=20)),
                ('price', models.IntegerField(default=0)),
                ('d_desc', models.CharField(max_length=30)),
                ('pub_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='P_cateye',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ce_name', models.CharField(max_length=30)),
                ('image', models.ImageField(default='', upload_to='diamond_images')),
                ('d_color', models.CharField(max_length=30)),
                ('d_clearity', models.CharField(max_length=20)),
                ('d_shape', models.CharField(max_length=20)),
                ('d_carat', models.CharField(max_length=20)),
                ('price', models.IntegerField(default=0)),
                ('d_desc', models.CharField(max_length=30)),
                ('pub_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='P_coral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coral_name', models.CharField(max_length=30)),
                ('image', models.ImageField(default='', upload_to='diamond_images')),
                ('d_color', models.CharField(max_length=30)),
                ('d_clearity', models.CharField(max_length=20)),
                ('d_shape', models.CharField(max_length=20)),
                ('d_carat', models.CharField(max_length=20)),
                ('price', models.IntegerField(default=0)),
                ('d_desc', models.CharField(max_length=30)),
                ('pub_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='P_diamond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diamond_name', models.CharField(max_length=30)),
                ('image', models.ImageField(default='', upload_to='diamond_images')),
                ('d_color', models.CharField(max_length=30)),
                ('d_clearity', models.CharField(max_length=20)),
                ('d_shape', models.CharField(max_length=20)),
                ('d_carat', models.CharField(max_length=20)),
                ('price', models.IntegerField(default=0)),
                ('d_desc', models.CharField(max_length=30)),
                ('pub_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='P_emerald',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emerald_name', models.CharField(max_length=30)),
                ('image', models.ImageField(default='', upload_to='diamond_images')),
                ('d_color', models.CharField(max_length=30)),
                ('d_clearity', models.CharField(max_length=20)),
                ('d_shape', models.CharField(max_length=20)),
                ('d_carat', models.CharField(max_length=20)),
                ('price', models.IntegerField(default=0)),
                ('d_desc', models.CharField(max_length=30)),
                ('pub_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='P_hessonite_garnet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hg_name', models.CharField(max_length=30)),
                ('image', models.ImageField(default='', upload_to='diamond_images')),
                ('d_color', models.CharField(max_length=30)),
                ('d_clearity', models.CharField(max_length=20)),
                ('d_shape', models.CharField(max_length=20)),
                ('d_carat', models.CharField(max_length=20)),
                ('price', models.IntegerField(default=0)),
                ('d_desc', models.CharField(max_length=30)),
                ('pub_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='P_pearl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pearl_name', models.CharField(max_length=30)),
                ('image', models.ImageField(default='', upload_to='diamond_images')),
                ('d_color', models.CharField(max_length=30)),
                ('d_clearity', models.CharField(max_length=20)),
                ('d_shape', models.CharField(max_length=20)),
                ('d_carat', models.CharField(max_length=20)),
                ('price', models.IntegerField(default=0)),
                ('d_desc', models.CharField(max_length=30)),
                ('pub_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='P_ruby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruby_name', models.CharField(max_length=30)),
                ('image', models.ImageField(default='', upload_to='diamond_images')),
                ('d_color', models.CharField(max_length=30)),
                ('d_clearity', models.CharField(max_length=20)),
                ('d_shape', models.CharField(max_length=20)),
                ('d_carat', models.CharField(max_length=20)),
                ('price', models.IntegerField(default=0)),
                ('d_desc', models.CharField(max_length=30)),
                ('pub_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='P_stone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=30)),
                ('image', models.ImageField(default='', upload_to='p_stone_images')),
            ],
        ),
        migrations.CreateModel(
            name='P_yellow_sapphire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ys_name', models.CharField(max_length=30)),
                ('image', models.ImageField(default='', upload_to='diamond_images')),
                ('d_color', models.CharField(max_length=30)),
                ('d_clearity', models.CharField(max_length=20)),
                ('d_shape', models.CharField(max_length=20)),
                ('d_carat', models.CharField(max_length=20)),
                ('price', models.IntegerField(default=0)),
                ('d_desc', models.CharField(max_length=30)),
                ('pub_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Pendent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pendent_name', models.CharField(default='', max_length=50)),
                ('image', models.ImageField(default='', upload_to='images')),
                ('price', models.IntegerField(default=0)),
                ('pub_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Ring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ring_name', models.CharField(default='', max_length=50)),
                ('image', models.ImageField(default='', upload_to='images')),
                ('price', models.IntegerField(default=0)),
                ('pub_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Sp_stone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image', models.ImageField(default='', upload_to='sp_stone_images')),
            ],
        ),
        migrations.DeleteModel(
            name='Stone',
        ),
        migrations.RemoveField(
            model_name='jewellery',
            name='category',
        ),
        migrations.RemoveField(
            model_name='jewellery',
            name='price',
        ),
        migrations.RemoveField(
            model_name='jewellery',
            name='pub_date',
        ),
        migrations.AlterField(
            model_name='jewellery',
            name='image',
            field=models.ImageField(default='', upload_to='jewel_images'),
        ),
        migrations.AlterField(
            model_name='jewellery',
            name='j_name',
            field=models.CharField(max_length=30),
        ),
    ]
