# Generated by Django 3.2.9 on 2022-01-05 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ram_app', '0003_auto_20211229_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bangels',
            name='image',
            field=models.ImageField(default='', upload_to='bangels_images'),
        ),
        migrations.AlterField(
            model_name='bracelet',
            name='image',
            field=models.ImageField(default='', upload_to='bracelet_images'),
        ),
        migrations.AlterField(
            model_name='earring',
            name='image',
            field=models.ImageField(default='', upload_to='earrings_images'),
        ),
        migrations.AlterField(
            model_name='mangalsutra',
            name='image',
            field=models.ImageField(default='', upload_to='mangalsutra_images'),
        ),
        migrations.AlterField(
            model_name='necklace',
            name='image',
            field=models.ImageField(default='', upload_to='necklace_images'),
        ),
        migrations.AlterField(
            model_name='nosepin',
            name='image',
            field=models.ImageField(default='', upload_to='nosepin_images'),
        ),
        migrations.AlterField(
            model_name='p_blue_sapphire',
            name='image',
            field=models.ImageField(default='', upload_to='bs_images'),
        ),
        migrations.AlterField(
            model_name='p_cateye',
            name='image',
            field=models.ImageField(default='', upload_to='cte_images'),
        ),
        migrations.AlterField(
            model_name='p_coral',
            name='image',
            field=models.ImageField(default='', upload_to='coral_images'),
        ),
        migrations.AlterField(
            model_name='p_emerald',
            name='image',
            field=models.ImageField(default='', upload_to='emerald_images'),
        ),
        migrations.AlterField(
            model_name='p_hessonite_garnet',
            name='image',
            field=models.ImageField(default='', upload_to='hg_images'),
        ),
        migrations.AlterField(
            model_name='p_ruby',
            name='image',
            field=models.ImageField(default='', upload_to='ruby_images'),
        ),
        migrations.AlterField(
            model_name='p_yellow_sapphire',
            name='image',
            field=models.ImageField(default='', upload_to='ys_images'),
        ),
        migrations.AlterField(
            model_name='pendent',
            name='image',
            field=models.ImageField(default='', upload_to='pendent_images'),
        ),
        migrations.AlterField(
            model_name='ring',
            name='image',
            field=models.ImageField(default='', upload_to='ring_images'),
        ),
    ]
