# Generated by Django 3.2.6 on 2022-01-11 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ram_app', '0005_p_stone_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(default='', max_length=50)),
                ('phone', models.ImageField(default='', max_length=50, upload_to='')),
                ('desc', models.IntegerField(default='', max_length=50)),
            ],
        ),
    ]
