# Generated by Django 3.2.6 on 2022-03-31 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ram_app', '0009_rename_name_sp_stone_sp_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='P_diamond_shape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ds_name', models.CharField(max_length=30)),
                ('image', models.ImageField(default='', upload_to='diamond_images')),
            ],
        ),
    ]
