# Generated by Django 3.2.8 on 2022-03-31 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ram_app', '0010_p_diamond_shape'),
    ]

    operations = [
        migrations.CreateModel(
            name='P_diamond_pear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diamondpear_name', models.CharField(max_length=30)),
                ('image', models.ImageField(default='', upload_to='diamond_images')),
                ('d_color', models.CharField(max_length=30)),
                ('d_clearity', models.CharField(max_length=20)),
                ('d_shape', models.CharField(max_length=20)),
                ('d_carat', models.CharField(max_length=20)),
                ('price', models.IntegerField(default=0)),
                ('d_desc', models.CharField(max_length=30)),
                ('pub_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='P_diamond_princess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diamondprincess_name', models.CharField(max_length=30)),
                ('image', models.ImageField(default='', upload_to='diamond_images')),
                ('d_color', models.CharField(max_length=30)),
                ('d_clearity', models.CharField(max_length=20)),
                ('d_shape', models.CharField(max_length=20)),
                ('d_carat', models.CharField(max_length=20)),
                ('price', models.IntegerField(default=0)),
                ('d_desc', models.CharField(max_length=30)),
                ('pub_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='P_diamond_round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diamondround_name', models.CharField(max_length=30)),
                ('image', models.ImageField(default='', upload_to='diamond_images')),
                ('d_color', models.CharField(max_length=30)),
                ('d_clearity', models.CharField(max_length=20)),
                ('d_shape', models.CharField(max_length=20)),
                ('d_carat', models.CharField(max_length=20)),
                ('price', models.IntegerField(default=0)),
                ('d_desc', models.CharField(max_length=30)),
                ('pub_date', models.DateField()),
            ],
        ),
        migrations.RenameModel(
            old_name='P_diamond',
            new_name='P_diamond_oval',
        ),
        migrations.RenameField(
            model_name='p_diamond_oval',
            old_name='diamond_name',
            new_name='diamondoval_name',
        ),
    ]
