# Generated by Django 3.2.8 on 2022-04-04 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ram_app', '0012_p_diamond_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='p_diamond_list',
            name='category_id',
            field=models.IntegerField(default=0),
        ),
    ]
