# Generated by Django 3.2.8 on 2022-04-04 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ram_app', '0013_p_diamond_list_category_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='p_diamond_shape',
            name='category_id',
            field=models.IntegerField(default=0),
        ),
    ]
